name: Autograding

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    - name: Download JUnit Platform Console Standalone
      run: |
        wget https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.7.0/junit-platform-console-standalone-1.7.0.jar
        mv junit-platform-console-standalone-1.7.0.jar junit-platform-console-standalone.jar

    - name: Compile and Run Tests
      run: |
        javac -cp .:junit-platform-console-standalone.jar SumEvenNumbers.java TestSumEvenNumbers.java
        java -jar junit-platform-console-standalone.jar --select-class=TestSumEvenNumbers
